### ISSUE TITLE
Replace "code" with "index"

### ISSUE THREAD

**Issue by gdalle** [JuliaGraphs/MetaGraphsNext.jl#17]
The whole `MetaGraphsNext` package uses the word "code" for what is usually called the index of a vertex. Maybe we could change that to get closer to `LightGraphs` conventions?

**Comment by gdalle** [comment]
Not sure who's still watching this, but @bramtayl I might move forward with this

**Comment by bramtayl** [comment]
I'm still watching. Still agree with https://github.com/JuliaGraphs/MetaGraphsNext.jl/pull/16#discussion_r703536513 but I'm ok changing it too.

**Comment by gdalle** [comment]
If I understand correctly, you worry that there may be a confusion between

- the method that takes a label and returns the vertex index (currently named `code_for`)
- the method `getindex` that takes a label and returns the vertex metadata

I hadn't understood this before, and I think you're right. What would you think about an approach *à la* MetaGraphs, where `getindex` actually returns the vertex index instead of the metadata? It would make some of the code a bit heavier, but I think we may gain in clarity?

**Comment by gdalle** [comment]
Of course that would mean going from a `Dict` to an `Array` for vertex- and edge-level metadata, but maybe we would even gain some performance in the process?

**Comment by bramtayl** [comment]
In base, `getindex` means roughly `get_at_index`: you pass an index to a dict, and Julia returns what exists at that index. It has the convenient `dictionary[index]` syntax.

`setindex!` roughly means `set_at_index!: you pass an index and a value to a dict, and Julia puts the value at that index. It has the convenient `dictionary[index] = value` syntax.

Because these have a convenient syntax, I wanted to reserve them for very common operations (using labels instead of codes, which I encourage). I think it might be confusing if we call codes indices, but pass labels (not codes/indices) to `getindex` and `setindex!`.

> `getindex` actually returns the vertex index instead of the metadata

That might be ok, but then how would `setindex! work?

**Comment by gdalle** [comment]
I see how this might be confusing, however due to the convenient `dictionary[index]` syntax, users will never call the function `getindex` themselves. As for `setindex!`, I think in my setting we would throw an error.
In the end it comes down to the most common operation you want to perform:

- if you love tampering with metadata, `g[label] = data` is fine
- if you love applying graph algorithms, `g[label] = index / code` is better because it gives you access to index-bases LightGraphs routines

**Comment by gdalle** [comment]
I guess I'm more used to building the metadata on vertices and edges once and for all, and applying lots of graph algorithms afterwards, which is why the second option made more sense to me?

**Comment by gdalle** [comment]
Closing this for now
