### ISSUE TITLE
Indices of node in induced subgraphs

### ISSUE THREAD

**Issue by AlexisSchOrange** [JuliaGraphs/MetaGraphsNext.jl#82]
Hello,
I've an issue regarding the function induced_subgraph with metagraphs: in the metadata, the index of the new nodes is not changed correctly.

See the following example:
```julia
mg = MetaGraph(
    Graph(),
    Int,
    Dict,
    Dict,
    "mg"
)
add_vertex!(mg, 1, Dict(:name=>"Thierry Henry"))
add_vertex!(mg, 2, Dict(:name=>"Kyky Mbappe"))
add_vertex!(mg, 3, Dict(:name=>"Benjamin Pavard"))
add_edge!(mg, 1, 2, Dict(:type=>"Love"))
add_edge!(mg, 2, 3, Dict(:type=>"Adoration"))
add_edge!(mg, 3, 1, Dict(:type=>"Respect"))

submg = induced_subgraph(mg, [2, 3])[1]
for i in vertices(submg)
    print(submg[i])
end
```

Will print a `KeyError: key 1 not found`

Perhaps I'm not using this correctly ? Otherwise, I've been looking in the source code, the `_copy_props!` is not working correctly ?

Muchas gracias,

**Comment by gdalle** [comment]
Hi!
This comes from a confusion on using a `MetaGraph` as a dictionary. The syntax `mg[i]` retrieves the vertex associated to a given _label_ (which can have arbitrary type), not to a given _code_, or index (which is always an integer). That is why the documentation recommends not using integers as labels as well, because it is very easy to mix up both concepts.
In the subgraph you create, the vertex labels remain `[2, 3]` but the vertex codes are renumbered to `1:2`. More generally, labels are preserved through graph modifications, but codes are not.
To fix your program, here are two options:
```julia
julia> for l in labels(submg)
           println(l, " - ", submg[l])
       end
2 - Dict(:name => "Kyky Mbappe")
3 - Dict(:name => "Benjamin Pavard")

julia> for i in vertices(submg)
           println(i, " - ", submg[label_for(submg, i)])
       end
1 - Dict(:name => "Kyky Mbappe")
2 - Dict(:name => "Benjamin Pavard")
```

**Comment by AlexisSchOrange** [comment]
Thanks for the fast reply! It is more clear now. Perhaps I should create me a new package `MetaGraphsButOnlyWithLabelThatAreSimpleIntegers.jl` ... Have a good day
